const now = new Date();

export const demoLineCodes = [
  { id: 1, code: "DOR", description: "Door and body hardware", createdAt: now, updatedAt: now },
  { id: 2, code: "XTD", description: "Extended line parts", createdAt: now, updatedAt: now },
  { id: 3, code: "FIL", description: "Filters", createdAt: now, updatedAt: now },
];

export const demoPartCategories = [
  { id: 1, name: "Body", description: "Body and exterior", createdAt: now, updatedAt: now },
  { id: 2, name: "Brake", description: "Brake system", createdAt: now, updatedAt: now },
  { id: 3, name: "Filter", description: "Engine filters", createdAt: now, updatedAt: now },
];

export const demoSuppliers = [
  {
    id: 1,
    name: "Keystone Auto Parts",
    contactPerson: "Sales Desk",
    phone: "718-555-0101",
    email: "orders@example.com",
    address: "New York, NY",
    accountsPayable: "0.00",
    createdAt: now,
    updatedAt: now,
  },
];

export const demoCustomers = [
  {
    id: 1,
    name: "MAC. CUSTOMER-DUNWIN",
    contactPerson: "Counter Account",
    phone: "718-555-0199",
    email: "mac@example.com",
    address: "Queens, NY",
    accountsReceivable: "128.44",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    name: "CASH CUSTOMER",
    contactPerson: "Walk-in",
    phone: "",
    email: "",
    address: "",
    accountsReceivable: "0.00",
    createdAt: now,
    updatedAt: now,
  },
];

export const demoParts = [
  {
    id: 1,
    sku: "924-990",
    name: "DOOR HINGE ASSEMBLY FRONT DOOR L",
    lineCodeId: 1,
    lineCode: "DOR",
    categoryId: 1,
    supplierId: 1,
    description: "Front left door hinge assembly",
    listPrice: "79.99",
    cost: "34.20",
    retail: "61.98",
    replCost: "36.50",
    avgCost: "35.10",
    price1: "58.98",
    price2: "55.98",
    price3: "52.98",
    coreCost: null,
    coreRetail: null,
    unitPrice: "61.98",
    stockQuantity: 2,
    minStockThreshold: 3,
    orderPoint: 3,
    orderQty: 6,
    orderMultiple: 1,
    stockingUnit: "EA",
    purchaseUnit: "EA",
    unit: "EA",
    manufacturer: "Dorman",
    mfgPartNumber: "924-990",
    weight: "2.40",
    imageUrl: null,
    partGroupId: null,
    isArchived: false,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    sku: "DL3614",
    name: "BRAKE PAD SET FRONT",
    lineCodeId: 2,
    lineCode: "XTD",
    categoryId: 2,
    supplierId: 1,
    description: "Front ceramic brake pad set",
    listPrice: "49.99",
    cost: "18.75",
    retail: "39.95",
    replCost: "20.00",
    avgCost: "19.10",
    price1: "37.95",
    price2: "35.95",
    price3: "33.95",
    coreCost: null,
    coreRetail: null,
    unitPrice: "39.95",
    stockQuantity: 12,
    minStockThreshold: 4,
    orderPoint: 4,
    orderQty: 8,
    orderMultiple: 1,
    stockingUnit: "SET",
    purchaseUnit: "SET",
    unit: "SET",
    manufacturer: "XTD",
    mfgPartNumber: "DL3614",
    weight: "4.10",
    imageUrl: null,
    partGroupId: null,
    isArchived: false,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    sku: "PH7317",
    name: "ENGINE OIL FILTER",
    lineCodeId: 3,
    lineCode: "FIL",
    categoryId: 3,
    supplierId: 1,
    description: "Spin-on oil filter",
    listPrice: "12.99",
    cost: "3.25",
    retail: "8.99",
    replCost: "3.50",
    avgCost: "3.35",
    price1: "8.49",
    price2: "7.99",
    price3: "7.49",
    coreCost: null,
    coreRetail: null,
    unitPrice: "8.99",
    stockQuantity: 28,
    minStockThreshold: 10,
    orderPoint: 10,
    orderQty: 24,
    orderMultiple: 12,
    stockingUnit: "EA",
    purchaseUnit: "EA",
    unit: "EA",
    manufacturer: "Premium Guard",
    mfgPartNumber: "PH7317",
    weight: "0.80",
    imageUrl: null,
    partGroupId: null,
    isArchived: false,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoPurchaseOrders = [
  {
    id: 1,
    orderNumber: "PO-1001",
    supplierId: 1,
    orderDate: now,
    orderTime: "09:12:00",
    type: "inbound",
    totalAmount: "438.00",
    status: "received",
    notes: "Demo receiving order",
    createdBy: 1,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoSalesInvoices = [
  {
    id: 1,
    invoiceNumber: "INV-1001",
    customerId: 1,
    customerNumber: "996",
    invoiceDate: now,
    invoiceTime: "10:24:00",
    type: "invoice",
    totalAmount: "61.98",
    status: "completed",
    poNumber: "",
    jobNumber: "",
    ref: "",
    vehicleYear: null,
    vehicleMake: null,
    vehicleModel: null,
    vehicleEngine: null,
    vehicleVin: null,
    notes: "Demo sale",
    createdBy: 1,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoCredits = [];
export const demoWarranties = [];
export const demoInventoryLedger = [
  {
    id: 1,
    partId: 1,
    transactionType: "sale",
    quantity: -1,
    balanceAfter: 2,
    referenceType: "sales_invoice",
    referenceId: 1,
    notes: "Demo sale",
    operatedBy: 1,
    createdAt: now,
  },
];

export const demoLowStockAlerts = [
  {
    id: 1,
    partId: 1,
    currentStock: 2,
    minThreshold: 3,
    isResolved: false,
    createdAt: now,
    resolvedAt: null,
  },
];

export function demoDashboardStats() {
  return {
    totalParts: demoParts.length,
    totalSuppliers: demoSuppliers.length,
    totalCustomers: demoCustomers.length,
    lowStockCount: demoParts.filter((part) => (part.stockQuantity ?? 0) <= (part.minStockThreshold ?? 0)).length,
  };
}
